### ISSUE TITLE
Recruit new guides & onboard them!

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1136]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by eduardovegap** [comment]
https://docs.google.com/document/d/1y4kaZM5nWypg1iVf4m-7yvv5BDB6odxwrhpnqGsX0ZE/edit

this document has been passed on to the guides, the following process has been followed:

- Meet with each of the volunteers (Manu, Gene, David) to be Guides and workshop with them the previous document. 

- Invite them to welcome people on the orientation channel, as well as getting familiar with the process (Mount Manu offered to curate the spreadhsheet).

- Invite them to join a orientation call, in order to get familiar with the orientation deck. 

- Have 15 minutes during the next WG call, to receive feedback and create the role "Guide" on the discord.

- Alternate with them the orientation call hosting, and 1-1s.

**Comment by ghost** [comment]
Thanks for curating the spreadsheet Mount Manu.

**Comment by eduardovegap** [comment]
Done.
We have opened a Thread on our discord called "Guides" to keep track of the microtasks.
