### ISSUE TITLE
Train new guides.

### ISSUE THREAD

**Issue by eduardovegap** [CommonsBuild/coordination#1263]
## 👇🏽  What is this issue about? Give as much detail as you can. 

We want to improve the Guide Role. So we will be having one guide in training for the next sprint. Will help with the update of the spreadsheet, as well as the FAQ. Plus we will be having feedback loops every two weeks to share experiences and updates with the other Guides.

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. 
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)

@

## 👀  Who should be in the loop about this issue?
@

**Comment by eduardovegap** [comment]
Costa has started doing work for Guides for the past two weeks: updating the spreadsheet, researching for FAQ document and the gitbook update. 

@Costa91 will start the second part of training by welcoming newcomers.

**Comment by mount-manu** [comment]
**Edu's Update:** This issue's done but we've opened a new one titled [Update new guides](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/commonsbuild/coordination/1304) for us to keep _honing_ the orientation process or rather the proxy between newcomers and the Commons: guides. The distinction is akin to learning how to ride a bike vs riding a bike with side wheels.

**Comment by mount-manu** [comment]
**Edu's Update:** This issue's done but we've opened a new one titled [Update new guides.](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/commonsbuild/coordination/1304) The new issue's purpose is to _hone_ our onboarding guides' competence since they are the proxy between newcomers and our Commons. The distinction between this closed issue and the new one is akin to learning how to ride a bike vs riding a bike with side wheels.

**Comment by eduardovegap** [comment]
@Costa91 has been almost fully onboarded and trained as a Guide. The only aspect left is to help him hosting 1-1. He will start shadowing Manu and Me next week.

**Comment by tamarandom** [comment]
Closing! Welcome @Costa91 !!
