### ISSUE TITLE
Conflict Mgmt Process

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#132]
## 📋   Anything to add?

Create a system to channel disputes and connect them to experts accountable for approaching parts involved and help manage the issue - solve it with graduated sanctions, or scaling the situation to more complex conflict management mechanisms.

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@

**Comment by JuankBell** [comment]
Forum post: https://forum.tecommons.org/t/gravity-general-process/173

# Gravity

“We can easily imagine people amusing themselves in a field by playing with a ball so as to start various existing games, but playing many without finishing them and in between throwing the ball aimlessly into the air, chasing one another with the ball and bombarding one another for a joke and so on (84).” L. Wittgenstein, Philosophical Investigations. (More about):
 

If there were no shared understandings, we wouldn’t be able to pursue any great tasks. That is why we need to be able to promote clear rules, and set the minimum boundaries, that will endow our system with legitimacy and let us build trust over it. Gravity is a proposal to apply an Alternative Dispute Resolution (ADR) Tailored System within our decentralized community, to address some of the challenges that naturally arise in all social structures.

The Gravity group will aim to support the TEC by:

Actively promoting trust, setting expectations, and managing conflict between individuals, the different groups, and the community as a whole. 
Recognize boundaries and Areas Of Potential Dispute, as well as explicit violations of boundaries between individuals, groups, and the community as a whole.
Supporting communication between community members and encouraging participation at all levels. Individually, in groups and inside the community as a whole.
Hold admin powers to manage systems of communication (Discord, Telegram, Forum, CV App) on behalf of the individual, the constituent groups and the community as a whole.  
Promote community resilience and long-lasting human relationships by proactively co-creating boundaries, discussion and exchange in a system of shared values.
As a group, take decisions regarding the implementation of graduated sanctions and commit to its participation with respect to all individuals, specially the ones that don’t follow to our terms and conditions.

What a community teaches is what establishes its culture, so it's important that everyone is aware of the collective agreements and expected behavior, which then are translated into processes and guidelines.

Our goal: People in the community recognize the agreements and culturally act coherently with the values of the organization. And If there is conflict, there are clear steps to follow in order to manage the situation for the effective search and implementation of solutions that respect the dignity of all parts involved.
