### ISSUE TITLE
Retro action: Make a list of priorities, critical work, for the TEC

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#1382]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Gideon suggests that we can use Pol.is. 
- 12 seed statements.
I propose we do this in the Stewards Council. 

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by natenatesoo** [comment]
@tamarandom This issue was part of our Retrospective to do action, but does not contain any tangible outcomes.  I will close this issue, and incorporate it into the most recent Sprint Retrospective with the development of a TEC Roadmap which includes the efforts articulated in the title here. 

If this needs to be maintained as an active issue, please feel free to re-open.

Thanks!
