### ISSUE TITLE
Comms Content Production & Distribution

### ISSUE THREAD

**Issue by jessicazartler** [CommonsBuild/coordination#145]
## 📋 Anything to add?

All content to be grouped for grooming & distribution/multi-purposing

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by mount-manu** [comment]
@jessicazartler would you please elaborate? Just got on the content publishing & distribution team so I might claim this.

**Comment by jessicazartler** [comment]
This issue is quite old so I don't remember the context.. what I would say is it could be helpful to have a content map for TEC like this one we made for CS https://www.notion.so/giveth/Commons-Stack-Content-Map-f572a1a856f84f4e99e5847d7b18efe7

I had to go hunting for all the Params links today.. so perhaps would be good to group articles in a context like that
@natenatesoo @markoprljic @tamarandom

**Comment by tamarandom** [comment]
Hi! This is quite an old one and it's also an Epic, so a container for all the issues related to the Comms content & distribution which has since moved to it's own repo here : https://app.zenhub.com/workspaces/tec-content-production-and-distribution-60549332d7d741001bbea827/board?repos=349409011

@jessicazartler or @mount-manu (or @chuygarcia92 or @natenatesoo or @markoprljic ) if you want to drop this idea (to follow the Commons Stack single landing page for evergreen content) that repo would be the best place to drop it so that it gets prioritized and planned alongside all the other issues in that repo now. 🤙🏽

**Comment by jessicazartler** [comment]
Thanks Tam!

**Comment by markoprljic** [comment]
IMHO I think it would be great to build up a page for such content and use that for onboarding people. I created the issue for that here https://github.com/CommonsBuild/content-distribution/issues/52

This issue can be closed if you ask me.

**Comment by tamarandom** [comment]
Closing old epics.
