### ISSUE TITLE
Legal / All 3rd Party Services T&C (Github & others)

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#243]

**Comment by liviade1** [comment]
https://github.com/aragon/aragon-wiki/blob/e4f9648b7ab7dc5992d908539ebd976854442941/docs/association/legal/CLA.md @Santigs @GriffGreen

**Comment by GriffGreen** [comment]
Thx livia!

**Comment by tamarandom** [comment]
Update : leaving open for @liviade1 feedback on this one.

**Comment by natenatesoo** [comment]
Update: Needs review, close to being done.

**Comment by iviangita** [comment]
Work in progress: https://docs.google.com/document/d/118ZLdlE7DoenME3c_IaZ4SWHqHsUkumA681ZYRNnjBY/edit?usp=sharing

Last comment from Shawn: I think the biggest thing the document is missing is a better delineation between "hey if you want to delete your comments off Discord and you can, go ahead" versus "hey you helped draft the Terms & Conditions and you can't just take that back because the community is using it"

**Comment by teresacd11** [comment]
This also aligns with the Code of Conduct and could be stablished in the same document as the content ownership one.

**Comment by iviangita** [comment]
@teresacd11 shared these [Collective Agreements](https://token-engineering-commons.gitbook.io/tec-handbook/tec-agreements-1/collective-agreements) that somehow have the similar content as the [3rd Party Application Standards](https://docs.google.com/document/d/118ZLdlE7DoenME3c_IaZ4SWHqHsUkumA681ZYRNnjBY/edit?usp=sharing)

Can we disregard this then? I think we can keep the document but no need to post it on Gitbook.

**Comment by mount-manu** [comment]
Although this is not critical, we might want to take advantage of our two new champions @teresacd11 and @Boonjue to move this forward, if only slightly. What do you guys think?

**Comment by Boonjue** [comment]
We can talk about this during tomorrow's call.

**Comment by tamarandom** [comment]
Closing old issues!
