### ISSUE TITLE
Onboarding COMMUNITY WHY video / Editing 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#310]
## 📋 Anything to add?

Edit the video based on the storyboard and provided video materials from member interviews.
Use any external video resources (preferably free and without copyright) to enhance the video.
Deliverbale: video high-quality, video exported for YT, small video clips to be shared on social media.

## ⏰ Urgency/Due Date/Blockers?

Before Hatch.

## ❓ Why is it important?

Promoting TEC.

## 🤼‍ Reviewer

@jessicazartler @markoprljic

**Comment by markoprljic** [comment]
@jessicazartler Do we want to ask Mount Manu (recently joined Discord) if he'd like to contribute to video editing?

**Comment by jessicazartler** [comment]
Sure, that would be great :D right now is the interview collection then planning to get on a call to discuss producing/editing

**Comment by markoprljic** [comment]
> Sure, that would be great :D right now is the interview collection then planning to get on a call to discuss producing/editing

@mount-manu Is taking this issue, waiting for [interviews](https://github.com/TECommons/coordination/issues/309) and [storyboard](https://github.com/tecommons/coordination/issues/391) to be sent.

**Comment by jessicazartler** [comment]
I am setting up a call to sync with him and discuss next steps.. interviews are ongoing and we aim to finish them all by end next week

**Comment by tamarandom** [comment]
Update : Assigned to Mount Manu.

**Comment by markoprljic** [comment]
Hey @mount-manu just checking in to see how you're progressing with the video. Let me know please.

**Comment by mount-manu** [comment]
@markoprljic Still editing and waiting on some final interviews to come my way. It's gonna be a tight fit for this sprint but I anticipate that by late next week I'll have a solid first iteration. After that, incorporating the feedback into a 2nd version with some final polishing edits will go into next sprint.

**Comment by markoprljic** [comment]
Thanks for the update Manu.

**Comment by markoprljic** [comment]
Inspiration videos:

https://twitter.com/discocoop/status/1349687411228504065

https://www.youtube.com/watch?v=AqjIWmiAidw

**Comment by markoprljic** [comment]
Someone made this https://eth10k.surge.sh/ and that made me think we could cut out interview audio in a similar fashion and have bg images, short clips accompany the narrative.

**Comment by markoprljic** [comment]
Storyline confirmed by Manu:

1. Introductions
2. Problems
3. Solutions
4. Community

Short version and long version to be created.

**Comment by chuygarcia92** [comment]
## **UPDATE ON COMMUNITY WHY VIDEO**:

For the past couple of weeks @mount-manu and I have been going through the video. You can check our progress so far in this private link: https://vimeo.com/548443347/41765bb857 

Some notes we are currently working on:

- Jake's interview is getting replaced by mine.
     * I'm adding a short definition for TE. 
     * I'm covering Jake's topics as well as introductions to Cultural Build and support for @markoprljic and Durgadas' interviews.
- We're correcting titles and names and replacing "Token Engineer" with proper WG lead title.
- We're changing the music and fixing volume levels.
- We're adding minor color correction and graphics.

Let us know if you have any suggestions or concerns!

**Comment by markoprljic** [comment]
Great update! :)
Looking forward to the next iteration and all points you mentioned to be fixed.

**Comment by laurenluz** [comment]
Hey @chuygarcia92 @mount-manu  - love the work you guys have been doing on the video - thanks so much for putting your heart into it!

A few comments:

1. I find it pretty distracting to see the little PIP views of the interviewers in the corners of some of the video shots. Especially in the interview with Zepti... screenshots below. It goes from his face and name, to his face and Jess. Anyway you can cut the video field? or add in some blurred side effect (like in Tam's video)?

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/10c80254-093b-4248-b4a4-c547fe4c8f1d)
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/ad048f0e-1456-4a58-90c4-04e510c47e74)

2. I really like how many you cover many aspects, but it feels a bit sudden to end right after community. I think the story arch would benefit by bringing it back to token engineering.... like a clip of a interview where someone is discussing how this community connection is a necessary element in the advancement of token engineering for the good of the collective. How we're all about building for the people... 

3. Would love an outro section and a call to action to bring the viewer to a natural culmination.... perhaps a little outro section with a call to action like "get involved" or at least a simple montage of different people saying "thank you" or "thank you for listening" or "we hope to see you soon"

4. I wonder if we could swap the music? would you be open to alternative suggestions

going to DM you a little video with a little demo of what I mean in #3 ;)

**Comment by chuygarcia92** [comment]
yes, I agree with @laurenluz about the PIP... does it take out a lot of quality because of compression if we crop it a little bit? @mount-manu 
if this is the case I could find a way to upscale it so we can still do it with less quality loss

**Comment by markoprljic** [comment]
Somehow I feel the first early draft version that @mount-manu demoed on the Comms call was more impactful and we lost that a bit. Would love to see that version again.

**Comment by divine-comedian** [comment]
If I understood correctly we're going to be shooting for a shorter video version that's around the 1:30 mark. 

I agree with Lauren, let's switch up the music if we can, feels a bit slow and cheesy. 

I have lots of feedback for how to shorten this video so we can hit our target length, nothing at all is personal but just a matter of how we can most efficiently convey our information, highlight our diversity, and celebrate our community.
INTRO:
We can probably slim down the multi-lingual introductions my suggestion would be to keep Griff, Ivi, Santi, Eduardo (or Juan Carlos), sebnem, marko, YGG and the other token engineers (zargham, simon) because of the variety of languages and quality of the audio captured in those languages and as well the importance of highlighting Griff and the Token Engineers

The shortened version  
PROBLEMS: 
I felt like between YGG and angela's clips they were redundant, YGGs response is a bit more encompassing, I feel it would be better to keep his.  replace Jake's blurb with a small recording of someone saying what he says to the effect of 'power is held in the hands of the few' because it is important to convey this and can be done quickly. 

SOLUTIONS:
Here we have two small clips from Griff, I would pick just one. I like his second clip around the 2:03 mark. Would be good to trim livi's clip, I think she says a good amount of information before she starts to stumble around 1:26. I enjoy the phrase where she mentions ethical design but the gap inbetween for her to get to her point takes up too much time. If there's any magical video wizardry that can happen to reduce the length of the clip and convey her two points of 'creating an economy to support token engineering' and 'ethically designed economies' with at least half as much run time.
Marko's I think is okay, the blurred out background I find is distracting but I'm not sure what the solution is.

COMMUNITY: 
Livi's is great, Juan Carlos has some good points but it takes too long to get around to them. I would pick between Zepti's (I favour zepti's because he mentions working groups and stewards) or Eduardo's clip but not both. Griff's clip could be cut in half, starting around the point where he talks about the relational fabric of the community which is a great phrase. 

I agree with Lauren, maybe a 5 second outro clip or CTA would be nice to tie off the end of the video.

**Comment by laurenluz** [comment]
This is a good place to get music samples: https://audiojungle.net/

Would love to know... what voice are we trying to covey here? "this is serious and important work that you should care about" "this is fun and exciting and you should join"? The music does a lot to set the tone and right now it's kind of painfully corporate, which I don't think does us justice!

Here's a quick example for something peppy/exciting (for the "fun" message): https://audiojungle.net/item/cool-motivational-indie-dance/31804598

There are for sure better options, just want to get the ball rolling.

**Comment by jessicazartler** [comment]
@chuygarcia92 I appreciate all the hard work. I didn't reach Simon DLR (from South Africa) to get his permission, so please remove him from the video. 

Some feedback:
-I strongly recommend removing Eduardo's soundbite about being "kids trying to change the economy" - nothing personal. but I don't think this is a great reflection for the work. 
-For as many times as people say Token Engineering in this video, the majority of the soundbites don't talk much about what it is, and there aren't any token engineers talking about token engineering. Might be good to include at least one clip of that.
-I also agree with a music change, and perhaps getting a few more voices 

Thank you for all of your hard work!

**Comment by chuygarcia92** [comment]
Our community video is DONE!! It's still unlisted on youtube but you can already take a look at it before the campaign to launch it right before the hatch:

https://youtu.be/vf1rOMDzw38
