### ISSUE TITLE
SEO Project 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#636]
## 📋 Anything to add?

Project brief. https://docs.google.com/document/d/18RlOZf_DhV149eZ-KPArBF0iFnwsi9SSLiMOg-vD0CU/edit

**Overview**
Google search results for “Token Engineering Commons” and “Token Engineering Commons medium” currently result in links that are 1) out of date or 2) badly out of date. This project will do a short study, analysis and then implementation of a plan to improve our SEO.

**Objective**
To optimize SEO for TEC so that our most relevant sites and links are highest on the results page of google, and other search engines with high market share. 

Analysis of the current state versus what the goal should be 
Review the best practices on how to improve SEO
Develop list of metrics for measuring improvements 
Implement, measure, tweak 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by mount-manu** [comment]
I got this, please assign.

**Comment by mount-manu** [comment]
I'll explain: the agency I'm a partner in (www.workowhole.in), although not listed in our services, knows how to do SEO for projects. We don't do it for free but I'm willing to cover the costs as long as the work translates into IHs. 

On the other hand, I can understand how our inability to help with the diagram due to circumstances I assume responsibility for, would make some skeptical as to our capacity to deliver... or, maybe, someone else is already doing it!

**Comment by tamarandom** [comment]
That is a very kind offer @mount-manu. 

This SEO project is being led by @natenatesoo with support from @iviangita and @chuygarcia92. I believe they have a bi-weekly sync on the progress of this project. Do reach out to @natenatesoo to see how you can help out!

This is an Epic, so a container for all the issues related to the SEO project. Epics are not native to Github so you have to use Zenhub to see them. You can see all of the issues within this scope of work. Have a look (at this one) here: https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/commonsbuild/coordination/636

**Comment by tamarandom** [comment]
Closing old epics.
