### ISSUE TITLE
[Infogrphic] Diagram of the DAO

### ISSUE THREAD

**Issue by jessicazartler** [CommonsBuild/coordination#64]
## 📋   Anything to add?
Hatch flow visual diagram so the community can get a visual on how our economy will work

## 🤼‍♂️   Reviewer
@tamarandom 

## 🔗   Work doc - inspirational links
TE Academy Stock & Flows
https://miro.com/app/board/o9J_kiNo1dQ=/

Example from Santi
https://forum.1hive.org/t/together-we-thrive/1278

**Comment by jessicazartler** [comment]
@GriffGreen were you planning to do a session with Jeff to refine your drawing before passing it to Marko? Thanks!

**Comment by jessicazartler** [comment]
![Diagram](https://user-images.githubusercontent.com/43972522/101225355-10a82e00-3646-11eb-8c2b-dacc2ce086f1.jpg)

**Comment by Santigs** [comment]
Sem and I created the chart to use in this week's Legal WG session but we also ended up using it in the first meeting of the Params WG.
It shows the process we will follow at launching.

The initial DAO, called Hatch DAO, will be a Dandelion DAO, it will be active only during the hatching period.
Hatchers (CSTK token holders) will be able to purchase TEC tokens depositing DAI (or xDAI or WxDAI) TEC token price still has to be defined. Every hatcher will only be allowed to purchase a maximum amount of TEC tokens, depending on the CSTK tokens he/she owns.
As DAI tokens get deposited, TEC tokens will be minted and the DAI tokens will go to a temporary reserve.
The hatching period will end if we reach the Max CAP or if we reach the Time period we define.
Once the hatching period (pre hatch) ends if we reach the Min CAP, we will move forward to Post Hatch period, otherwise, all DAI will be refunded to the hatchers and the process will stop.
At this time we will split the total DAI in the temporary reserve into two: The Reserve Pool to feed the future bonding curve and the Funding Pool for projects.
A proposal will be submitted for everyone to vote to migrate to a final ABC+CV DAO (Augmented Bonding Curve + Conviction Voting). During this period, anyone will be able to redeem their purchased TEC tokens if he/she does not feel comfortable with the process, but there will be a "tribute" percentage donated permanently to the DAO. Let's say you invested 100 DAI, you may get back only 70 DAI, it will depend on the value of the Tribute we finally determine.
If the proposal succeeds and we move forward, there will be an execution period, during this time, anyone not supporting the proposal will still have a chance to redeem their TEC tokens back to DAI, leaving a "tribute" as a donation.
If the proposal does not succeed during the voting period, a period of time (proposal buffer) will be needed before a new proposal is launched to try to succeed.
Every proposal will have a tollgate fee, which is the amount of money required to launch it.

When the proposal succeeds and after the execution time we will migrate the TEC tokens and the DAO into the final DAO where ABC+CV will be implemented, The initial hatching DAO will remain useless.

**Comment by Santigs** [comment]
The diagram is a way to visualize and understand the process and all the parameters we will de discussing together to launch.
Among others:

Total hatch time.
Min and max Cap
TEC token price
Amount of TEC tokens a hatcher will be able to purchase with every CSTK token
Split % between Reserve and Funding pools
Tollgate fee amount
After proposal buffer
After execution period.

As well as some of the Dandelion parameters we are also discussing in the Params WG.

**Comment by jessicazartler** [comment]
FROM SEM: 

Please take into account we are still discussing if splitting the funds right after the post hatch or once we have migrated the dao. We also doesn't have clear what can IH holders do with their tokens (there is the possibility that they can cash out immediately if the min goal is reached in the fundraising, more details in the legal wg session of last Friday)

So the diagram is not definitive

**Comment by jessicazartler** [comment]
FROM JEFF: High level views for visuals/explanations

![20201209_125050](https://user-images.githubusercontent.com/43972522/101686137-7ec16c00-3a1d-11eb-8720-3fa6867e1fae.jpg)
![20201209_125042](https://user-images.githubusercontent.com/43972522/101686139-7ff29900-3a1d-11eb-9d2c-b060addd69e5.jpg)

**Comment by jessicazartler** [comment]
Should we use this one? Or break it down into parts as Jeff is thinking?
https://forum.tecommons.org/t/launching-in-2-parts-first-hatch-dandelion-then-vote-to-add-abc-cv/85/10?u=santigs

Thoughts on best representation/communication for this... please let me know your feedback @Santigs @GriffGreen @Jeff-Emmett

**Comment by tamarandom** [comment]
@sembrestels working on something similar. Link!

**Comment by jessicazartler** [comment]
Updated via @GriffGreen - Eduardo, Jeff and I have a meeting tomorrow to work on turning this into content and explore options maybe an animated video..
![Hatch diagram](https://user-images.githubusercontent.com/43972522/107975032-789fbc80-6f85-11eb-8787-c00750b9bda8.jpg)

**Comment by freedumbs00** [comment]
Just a thought but we could make this a fun meme/video with lego people and breakdown the process and share it in almost a little story like way.

**Comment by markoprljic** [comment]
Yes, I think @eduardovegap was considering hiring someone to create a video for this BUT now we also have @mount-manu who could be interested in supporting this issue.

**Comment by jessicazartler** [comment]
I was pulled off this issue to work on other things - I have a sync with Manu next week and could pull Jeff in to show what he has drawn out so far and see where Manu can take it.. those circle diagrams are missing a few things and hard to read - the miro board drawings are much more agent centric and easier to understand the context https://miro.com/app/board/o9J_krl8Cv0=/

@eduardovegap let me know if you could jump in also to see if Manu's solution or your people would be more efficient to get this done - I am happy to help if any content is needed - I had some other ideas to bounce off of you to see the best way to break this up/explain it - otherwise you guys can take this forward - I can just be here to support..

**Comment by eduardovegap** [comment]
@markoprljic yes! we can meet with @mount-manu to see posibilities, let me know when you guys are available, i started working with Mitch on a script for the visuals, this diagram will be much helpful,

**Comment by jessicazartler** [comment]
Scheduled for Tuesday 10am EST / 4pm CET - meeting of the minds to sync on hatcher content - go team! Jeff/I will support the scaffolding then Mitch/Eduardo/Manu will run with it and create from there :D

**Comment by eduardovegap** [comment]
@jessicazartler shall we work on this issue for this diagram visuals? Can we assign Mitch and Manu to this one? or shall we create a new one?

**Comment by jessicazartler** [comment]
Go for it - you can use this one

**Comment by Jeff-Emmett** [comment]
I believe this issue was originally also for a visual of the TE Commons
"system flow", for which I also drew the below diagram. (This can
definitely wait until the hatch diagrams are done.)

I think diagrams like the one below (can be found on the same TEC Miro
board) will be helpful for people to understand the actions available to
participants in the TEC, when TEC comms moves on to explain how the overall
system will work.

[image: image.png]

**Comment by tamarandom** [comment]
Hey @eduardovegap Can you share the latest on this one?

**Comment by tamarandom** [comment]
Hello @eduardovegap ! This is assigned to you but it's @mount-manu that is taking this on, right? I want to confirm before swapping it over to him.

**Comment by tamarandom** [comment]
Hey @mount-manu  - @eduardovegap signaled this is yours, so swapping the ownership to you.

**Comment by mount-manu** [comment]
The understanding @eduardovegap and I had was that I'd assist him, not that I'd assume ownership of the task. So, no @tamarandom I have no capacity for this during this sprint. Leave it assigned to me if it's ok for it to be completed during the next sprint.

**Comment by tamarandom** [comment]
Hey @mount-manu thanks for this update.  In this case, it should probably not be assigned to you. I'll add it to the Comms Agenda where we can group think on whether we still need it, what exactly we need, who is doing what and who should own quarterbacking it through.

**Comment by markoprljic** [comment]
Note to self:

- diagram from the hatcher's perspective as they go through the journey
- Tamara has a newer version in Miro
- needs visual design
- questioning the value add of doing this

**Comment by markoprljic** [comment]
Updated graphic from Tam in Miro board https://miro.com/app/board/o9J_krl8Cv0=/

- Something to be published as an infographic 
- Commons Swarm example
- When do we need this? ASAP
- Value in sharing and easily talk about the Hatch 
- To not have a lot of text and visually walk through someone through the 3 phases 


@manualzuru assigned to this issue
@tamarandom ownership/reviewer

**Comment by jessicazartler** [comment]
@manualzuru or you meant @mount-manu ? :D

If manu alzuru is back, that would be amazing!!!

**Comment by markoprljic** [comment]
Ah damn, thanks Jess, yes I meant @mount-manu :)

**Comment by tamarandom** [comment]
Sprint update : 

@mount-manu and I had two good sessions to go deep into the hatch Process and he will take the miro board version and see whether he and his team can either 

1) make improvements to the original to make it more crisp and clear. 
or 
2) make a new stand-alone version from scratch. 

He shared he is expecting to have a version to share for feedback by the end of this week.

**Comment by tamarandom** [comment]
Update :  @mount-manu's designer has had a family emergency and was not able to make progress on this. Fortunately Durgadas offered to take a crack at it!! 

Thanks @mount-manu for taking this on in the first place. Hopefully, your designer's family recovers quickly. 🙏🏼

**Comment by markoprljic** [comment]
This will probably fall into the next sprint so I'll move it to the Product backlog. 

cc/ @chuygarcia92

**Comment by jessicazartler** [comment]
@tamarandom @Jeff-Emmett and I worked on diagrams in this piece https://medium.com/commonsstack/whats-in-a-hatch-3799a398243a

@tamarandom do you think we need anything further? Perhaps we will when we do an article on Phase 2, the Commons Upgrade, and show the side where people will be buying and selling to the bonding curve/CV for proposal funding.. 

Should we change this issue to the title "Hatch Diagrams" and close it, and open a new issue for each/and any other diagrams that are needed for specific pieces? @markoprljic

**Comment by tamarandom** [comment]
I was thinking the same @jessicazartler. 

We have this (below) thanks to everyone who has given such great feedback as it was evolving. I know it could be a lot better but it's good enough for right now. The good news is that I'm in touch with a creative director that is interested in taking a crack at making this more pleasing to the eye/ brain and I will open a new issue for that one. 

Hallelujah, this issue is finally CLOSED. 

![Screen Shot 2021-04-30 at 2.26.56 PM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/810af7ec-a07c-49cb-bd01-690d0cb1a182)

![seinfeld.gif](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/03448113-429b-43d0-ba9d-5437b58f5cfd)

**Comment by jessicazartler** [comment]
Awesome! Thank you to everyone x 2 and hallelujah indeed!!!! hahaha Yay for the creative director - thank you and good luck with exploring that collab
