### ISSUE TITLE
Monitor Discord new members, are people still getting stuck or is it getting better?

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#671]
## 📋 Anything to add?

The onboarding journey had bad metrics. There were some steps taken to improve that (see #499).

Are they working? 

**Criteria for success**
- Method to measure what percent of new joiners are able to see/join all channels with ease, what percent get stuck. 
- Tweak/test (if necessary). What can be improved?

Note: There is a stop-gap measure of @danelsuga, as part of her responsibilities as onboarding coordinator, DM'ing those that get stuck on the "green check box" step. We will know more over the next sprint about whether that is working or not. When we checked earlier this week, 7 of the last 10 people that landed in the server did not have the "acknowledge CC" role and so are not able to see or join any channels. 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@danelsuga

**Comment by danelsuga** [comment]
I contacted @liviade1 and @JuankBell today to see if we could modify the message to make it clearer to new joiners that they will not have access to anything if they don't green-check the message. Perhaps if we make it supremely evident right from the start, that might help alleviate the problem.

**Comment by danelsuga** [comment]
Note also that of all the new joiners whom I contacted, none of them at this point have returned to green-check the message.

**Comment by Vyvy-vi** [comment]
The edits to the messages have been made. Hopefully, that should help emphasize that the reaction is necessary for getting access.
I think it would be more easily classified if we know how many of the users are actually human. The site made in #499, hasn't been adopted as of yet, however, once it is, we could be more sure about how many members are bots and how many humans(and in future, no new bots could infiltrate the server)

**Comment by tamarandom** [comment]
Oh no! We don't have a champion for this. @Vyvy-vi would this be something you can take on? I imagine it will remain a repeating issue for the next few sprints while we observe the results of changes. @danelsuga is looking at when new members are stuck (i.e., not checking the green box) and reaching out to them directly. A few of us are also manually assigning the role when we see someone we know personally that is in that limbo state. I did that this week for Tyler from BlockScience. 

For the site made in #499, are the next steps to rollout that somewhere? I don't see them in the issue itself.

**Comment by tamarandom** [comment]
@tamarandom to find a champion. (Hope it can be you @Vyvy-vi )

**Comment by Vyvy-vi** [comment]
Yes, I can take this next Sprint.
The discord invite site is useable, the next steps would be -
- Delete all invites to the server and use https://discord.tecommons.org/ for all discord invitations. (*note- we might need to discuss with Comms/respective WGs about editing links to the calls. We might need to tweak this a little bit to ensure that this can link to the discord voice channels too, but without the invite)
- Enforce prevention of discord invite making permissions

**Comment by tamarandom** [comment]
Hero!

**Comment by Vyvy-vi** [comment]
> Yes, I can take this next Sprint.
> The discord invite site is useable, the next steps would be -
> 
> * Delete all invites to the server and use https://discord.tecommons.org/ for all discord invitations. (*note- we might need to discuss with Comms/respective WGs about editing links to the calls. We might need to tweak this a little bit to ensure that this can link to the discord voice channels too, but without the invite)
> * Enforce prevention of discord invite making permissions

However, I don't know if we want to move forward with using the site

**Comment by Vyvy-vi** [comment]
I've looked a bit into the server onboarding process, and here's some takeaways-
1. Maybe we should have a hybrid approach, where we can use both normal discord links and the [`discord.tecommons.org`](https://discord.tecommons.org) website. I'll have to change the website workflow a bit and tweak the bot(store the user ids of the people that filled captcha, and are verified as "Human"). Whenever, anyone enters the server, if their id is not on the list, the bot removes them from the server, and DMs them a message about how to fill captcha on the site, and redirects them to discord. This might help us in inviting people directly to calls.

2. Maybe, we should add a pre-text to invites about the onboarding process.
-> GO to `discord.tecommons.org`
-> Verify you are human by filling captcha
-> Open the server and read the rules and policies, accept it by reacting with a ✅ 
-> Go to the call

3. A large share of people, that haven't acknowledged that message, fall into 4 categories:
- The ones that joined before the bot was set up(not a lot of people(5-6?), and they _do_ have access to the server since the `Acknowledged CC` role was added to them manually)
- The bots (not sure about the exact distribution here, but atleast 30 bots or more) I'm not sure how we filter these out and remove them. I think most probably we can kick all of the ones that didn't respond to Katy during onboarding, and send them a message stating, they can join back in via the site. (might ensure that the humans join)
- The ones that didn't go through the onboarding process.
- The ones that weren't able to go through the onboarding process. I think we need some community feedback from people that just joined. I'm wondering if maybe we can get some feedback from people that got stuck, who just joined about what can be done better, and on which step did they get stuck.

Should we host a Sync call for discussing next steps?
(Q) from whom should I ask with regard to the onboarding process and what time would work for people concerned about this?)

**Comment by danelsuga** [comment]
Thank you, @Vyvy-vi, for all of this great information. I really like your solutions, and I'm totally down for a sync. I think that's a super idea. Timeframe availability can be flexible especially if it's you and I, since I am CET and you are India. Ideally we could do your early afternoon/my morning. It depends on who wants to join. I am in 100%. Let's get feedback from @tamarandom.

**Comment by Vyvy-vi** [comment]
*Though my personal time zone sorta matches UTC +1, so timing shouldn't be an issue.
I'm most available from 6.30pm CET to 10.30pm CET and 1.30pm - 3.30pm CET

**Comment by tamarandom** [comment]
Closing this issue now! Thanks for everything @Vyvy-vi
