### ISSUE TITLE
Emphasize that there is an action required on this landing page 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#680]
Something like "You must READ AND ACCEPT the below to see and join channels on this server!" in big red letters at the top.

![Screen Shot 2021-05-03 at 11.15.20 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/64d64ff7-e609-4f80-86e4-e17c66ec68fe)##

 📋 Anything to add?

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by tamarandom** [comment]
Looks like some people think it's THIS check box they have to check and not the above one. 

![Screen Shot 2021-05-03 at 11.38.20 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/e6478fc4-ef16-4bf9-9702-72b31b4c59f5)

**Comment by danelsuga** [comment]
Hi @tamarandom. I cross-checked the wrong green-checks (the ones on explanatory message of @JuankBell ), and most folks had green-checked **both** messages, however at least two did not. I since informed them (and am keeping track of all that info on the contributor log). 

Can some one please help me change the header of this message on the "start here" page? It really needs to indicate asap that folks must green-check the message IN ORDER to have access AT ALL. Nowhere does it explain that they will not gain access to channels without the green-check. (It only says that you need to green-check to confirm that you understand meetings are recorded, etc.) I think folks are either not reading the end or simply do not want to green-check because they do not understand it is fully barring them from everything. @liviade1 @Vyvy-vi ? Thanks!

**Comment by tamarandom** [comment]
Hey @danelsuga thanks for checking on that. I am not able to edit that message myself but @JuankBell will be able to help you with editing or posting an updated welcome message on the #start-here channel.

**Comment by tamarandom** [comment]
Hey @Vyvy-vi , @JuankBell is sending me to you. ;) Can you help @danelsuga with access to edit or replace that starting message, please.

**Comment by Vyvy-vi** [comment]
I think there are a few edits needed-
1. The channel header(description)
This can be edited by-
   - Click on the settings symbol next to the channel name in the listing!
   [discord channel setting](https://images.zenhubusercontent.com/6032294817c1a127a267f9de/030f28f9-c5a6-4e3c-ab02-3079b6cc5d73)
    - Edit the `Channel Topic` field in the `Overview`
    - Save Changes
2. The old message can be edited, or maybe we can make a new message in there(Whatever works)
     Editing is slightly tricky(You can send the updated text, and I'll try and update the old message)
     If making a new message, this can be done from https://carl.gg/dashboard/810180621930070088/reactionroles

**Comment by danelsuga** [comment]
Thanks, @Vyvy-vi ! 

1. I edited the "channel topic" for grammar but did not otherwise change that message. It should probably be changed to something clearer, however, such as: "In order to access any TEC Discord channels, new joiners must read and accept the following rules."

2. To edit the old message, I suggest the following (@tamarandom, @liviade1, @JuankBell, could you look at this please?): 

Welcome to the TEC Discord. 
[and in red] You must :green_check_: this message in order to see and join any TEC channels!

By clicking the :white_check_mark: at the bottom of this post the participant agrees to be recorded and allows the use of the recorded material and its content when accessing a TEC Meeting and/or utilizing the platform in which such meetings are being held.

We're glad to have you here! This Discord server is for everything Token Engineering Commons related, including getting help for our projects, coordinating development, discussing funding proposals and hanging out.

TEC Meeting Protocols, Terms, and Disclaimers:
The Token Engineering Commons or TEC (“we”, “us”, “our”), a blockchain-based entity on the Ethereum/xDai network, encourages proactive transparency. Our online meetings may be live-streamed/recorded and published on any of our official communication channels or materials for transparency and social engagement purposes.
For more details, read our Meeting Protocols, Terms, and Disclaimers. 

TEC Channels & Links
Here will find an overview of links to our channels and resources. 
https://tecommons.org/join

TEC Youtube
The TEC is proactive to transparency, and so our Working Group sessions are all available on Youtube. https://www.youtube.com/channel/UCagCOhMqMNU29rWx259-tcg

TEC Blog
And read the latest posts on our blog: 
https://medium.com/token-engineering-commons/

TEC GitBook
https://token-engineering-commons.gitbook.io/

TEC Forum
https://forum.tecommons.org/c/welcome-to-the-tec/12

Enjoy your stay! See you soon.

**Comment by Vyvy-vi** [comment]
@danelsuga  How does this look: https://discord.com/channels/810180621930070088/810183289863798815/816366230549823539 ?

**Comment by danelsuga** [comment]
Thanks, @Vyvy-vi! That is really helpful! Looks great. 

If I needed to tweak it, what would be the best way to do that? I think, for example, we might want to swap out links at some point (I took out an old link already for example, but it would be good to put back in an up-to-date onboarding link) and update the message itself (I did not change the original message at this point) as well as general editing. I'm sure other folks will have input too. 

Also, @Santigs, would you be able to double-check that such a message is inline with regulations we need to follow? The things that changed were:

- added red message at the top
- placed the info re: recording at the beginning
- changed some info links

Thanks, gang.

**Comment by Santigs** [comment]
We will go over it in the WG meeting next Friday

**Comment by Vyvy-vi** [comment]
> If I needed to tweak it, what would be the best way to do that? I think, for example, we might want to swap out links at some point 

There is a bot command that you would have to run(this could have been straightforward, but the Carl Bot's developers screwed up the easier method and I think a fix wouldn't be comming any time soon)

Maybe next WG call or anytime you're free, I can show how to edit the message in chat.

Another way might be to delete that message and make a new one whenever needed

**Comment by danelsuga** [comment]
Thanks, @Vyvy-vi! I'm going to close this issue now.

**Comment by danelsuga** [comment]
Hi @Vyvy-vi. This issue was mentioned again in #686. I'm reopening this one since there were some useful details. @Vyvy-vi, can we sync to rewrite or edit? Thank you.

**Comment by danelsuga** [comment]
Synced with @Vyvy-vi to fix this issue. He recoded it, and it's up and running according to Santi's guidelines, also with the message in red to click the checkmark at the bottom.

**Comment by Vyvy-vi** [comment]
Closing this issue for now.
There's further discussion on this topic on #671
