### ISSUE TITLE
#join-here welcome message improvement on Discord

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#686]
## 📋 Anything to add?

Yesterday, @liviade1 mentioned in passing that it might be better if the message was shorter. (Need to check in with her on what her specific thoughts were about this).

Looking at the welcome message again, we should at least move the warning message to the bottom (as well as the top). Unless your discord is quite long, the warning message does not even show up on the screen. Separate the disclaimer from the welcome part of the message? 

![Screen Shot 2021-05-13 at 9.32.25 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/ad8f154d-9602-43ef-855e-5533545ea5f9)

![Screen Shot 2021-05-13 at 9.32.45 AM.png](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/d248deef-89f0-4cf1-ba42-575e8e25cb8c)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by danelsuga** [comment]
Plan to sync with @Vyvy-vi to rewrite the message as suggested.

**Comment by danelsuga** [comment]
Reopening #686, which is about the same thing with more details.

**Comment by danelsuga** [comment]
Santi has just given me the legal guidelines for changing the message, which includes switching the first two points (first two sentences basically) so that the info regarding being recording comes first. 

I am syncing with @Vyvy-vi to take care of that as well as adding another request at the bottom of the message to check the message (as suggested by @tamarandom). 

Also per Santi and his Advice Process gang (I don't know who), I will also add the calendar and Twitter.

**Comment by danelsuga** [comment]
Santi has just given me the legal guidelines for changing the message, which includes switching the first two points (first two sentences basically) so that the info regarding being recording comes first.

I am syncing with @Vyvy-vi to take care of that as well as adding another request at the bottom of the message to check the message (as suggested by @tamarandom).

Also per Santi and his Advice Process folks (I'm not sure who), I will also add the calendar and Twitter.

**Comment by danelsuga** [comment]
Synced with @Vyvy-vi to fix this issue. He recoded it, and it's up and running according to Santi's guidelines, also with the message in red to click the checkmark at the bottom.

**Comment by Vyvy-vi** [comment]
Are their any more changes needed, or should we close this issue?

**Comment by danelsuga** [comment]
2/3's of new joiners seem to be clicking the green check. That is better than before. I don't know if changing the message anymore will increase that. We can continue to tinker as need. I'll close this issue for now.
