### ISSUE TITLE
Manage this:  Impact Hour holders that have not activated their Trusted Seed membership that their tokens will not be valid after the Hatch date

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#704]
## 📋 Anything to add?

-Impact hours will be awarded at Hatch time. 
-Anyone that currently has Impact Hours but have not activated their Trusted Seed membership will lose them at Hatch time.
-We have an xls of all Trusted Seed activations
-We have an xls of all Impact Hour holders
-We need to cross reference this list to identify those that have not activated 
-Reach out to those individuals and let them know how that they will need to activate their membership to claim the IH reward

@cranders1 - is it possible for you to cross reference that list to output non-activated IH holding individuals? 
@eduardovegap - can you lead reaching out to them? 

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by cranders1** [comment]
Yes, I will assist on this. 
Need to review sheet status and versioning.
I was active on this task in the early months via tg, perhaps solo. Think I contacted close to 150 individuals. Stopped that activity several months back but def kept records :)
Should pry schedule a work sesh...

**Comment by eduardovegap** [comment]
@cranders1 Let's talk!

**Comment by cranders1** [comment]
i have the IH-TS activation crosstab sheet ready to share.

@eduardovegap where is the best place for it? TEC_curate? A fresh sheet?

@tamarandom does edu have access to sensitive sheets with addresses etc? was going to share but couldn't find him in the already permissioned docs. please advise. no offense edu.
the partial is already in the swiss assoc sheet under 'craig_airdrop_working' tab

unfortunately, how i got to where i got is a bit convoluted. would be better to describe in person.

also, the full IH list only has TG and/or discord handles. no email addresses.
we do have partial email lists (commonstack authorization email campaign hubspot ~125 & the CSTK swiss activation sheet ~140),  but that is another layer of parsing.

summary stats as of 5/7 PQ (approx):
IH individuals - 386 (67 new)
TS accept - 189
TS activate total - 140
IH-TS activate - 99

So, 99/386. 287+ individuals to contact via TG & discord, and likely an email campaign at some point pre hatch completion.

many months ago, i contacted 149 individuals on TG, but only prompting them to apply for the TS. those records included.
i have not contacted anybody about activating their TS via the swiss app.

bit of work ahead of us. i am happy to help out if needed on TG reachout. 
since i have a history, i could follow up with those already contacted but not yet activated.
if u provide me with a boilerplate language, i can begin and personalize each. or i can just fire away 😃

**Comment by eduardovegap** [comment]
Thank you Craig! 

Not taken at all! 
Working on it, sent you a message after checking the document provided, will probably prioritize people that have been accepted as TS and that have earned IH. After that, I will pass to the rest of the list.

**Comment by tamarandom** [comment]
Hero, Craig, hero!

"bit of work ahead of us. i am happy to help out if needed on TG reachout." <-- YES! We can use all the help we can get here actually. 

Looking at the sheet and it's not so bad actually. There are only 28 people with more than 20 IH that have **not** activated their trusted seed. We start with them. And then 60 more with more less than 20 but more than 4 IH.

**Comment by cranders1** [comment]
Revised the sheets. Now should be picking up all matches.
Not much change though with respect to swiss app activation. Don't think that source sheet updated since last run through.

yes, just lmk when i have a list of folks to contact.

**Comment by eduardovegap** [comment]
I added a new column to @cranders1 called "reached" to mark which ones I have contacted.

**Comment by tamarandom** [comment]
Hey @cranders1, there was an airdrop yesterday. Is there an easy way to update the Hatcher Tracking tab to reflect the newly activated?

**Comment by tamarandom** [comment]
In progress and will continue into the next Sprint. 

Currently on pause during the CSTK burn but that will be resolved quickly and we will continue outreach!

**Comment by cranders1** [comment]
Sheets updated with this week's swiss apps. Will update IH after tomorrow's PQ.

Started some forensics on individual cases with mismatches and other tomfoolery. All of these cases likely need individual attention/revision in the accounting.

SwissAsso-0207:
'craig_airdrop_working' - see craig notes, scroll to bottom, red

TEC Impact Hours & Addresses:
'Hatcher Tracking' - see Forensics column, red

4  categories thus far:
NO addresses : YES master - IH Sheet, Addresses tab needs to be updated from CSTK master (@GriffGreen / @knobsdao ?)
different address TS & Swiss - needs master reconciliation
not in IH but Swiss act - could be mismatched handle or address, needs master recon
no handle in master - not sure, likely a mismatch or multi-address situation

Seems all of these fall into hmmmm abyss, and each need a separate look by somebody with the authority to say which is the correct path.

**Comment by knobsdao** [comment]
Hey @cranders1! I updated the addresses tab from the master from row 637 onwards.

Also, I added "default handle" where there was one and prioritised Discord over Telegram as a second option (this can be changed if needed be). The "YES" Column D are if they are in the registry and "For Review" means they were rejected or might be (feel free to delete this).

Let me know if I can do anything else for forensics!

Now that we cleaned a lot of spreadsheets during the burn, we could probably make this one better and automate some data filling as in the CSLOVE airdrop sheet. Decided not to change anything for now as I wasn't sure if this would help or complicate things - but do let me know any way I can help out with TS data.

**Comment by cranders1** [comment]
Awesome @knobsdao. Much thnx.
Will dive in and get back with any questions.

Definitely up for automating. But yeah, it needed to be cleaned and somewhat standardized first.
I always feel kinda silly bothering you to update things.

Don't change anything just yet.
After I harvest the updates, I will set up a sync to do some automating.

**Comment by eduardovegap** [comment]
Shall we keep next sprint label since we are going to do one last push? @tamarandom

**Comment by eduardovegap** [comment]
last changes and updates has been added to the spreadsheet: including pings and change of the last two requested eth address. 

Can we close the issue? @tamarandom
