### ISSUE TITLE
Deploy the new templates on Github! 

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#710]
## 📋 Anything to add?

For issues #365 and #668 both text are in this doc, 
https://docs.google.com/document/d/1r1D0ZTbOCf3RQs2K6W-uOWniqzvJo5WDASmo5pYyArU/edit

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Vyvy-vi** [comment]
![Screenshot 2021-05-26 at 11 29 01 PM](https://user-images.githubusercontent.com/62864373/119712494-43f1aa00-be7e-11eb-9ab0-8633b5666ebe.png)

I've set up the templates. (Ignore the Security part, since that's due to how my account is set up)
I'll open a Pull Request in a while, and we could maybe discuss if there is some change needed in the description text.
