### ISSUE TITLE
Discuss the role of internal comms for transparency

### ISSUE THREAD

**Issue by Zeptimus** [CommonsBuild/coordination#715]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

##🧍🏻‍♀️🧍🏻‍♂️ Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by Zeptimus** [comment]
We discuss it on the last transparency call but we still not have a clear definition

**Comment by iviangita** [comment]
The issue came from a situation when one community member didn't know that the Impact Hour will be lost if they don't activate their TS membership, which we think is a general comms issue rather than an "internal comms" issue.

@Zeptimus and I discussed that while the Transparency WG should do its part in ensuring that an important information like this should be clearly and well communicated to the community members, we think that this issue can be better addressed by the Communications WG in the future and the Transparency can support.

The action we are taking for this is to discuss the issue with Comms and they can take it from there, with our support if needed of course. :)
