### ISSUE TITLE
Nice discourse feature, can we apply this to our own?

### ISSUE THREAD

**Issue by tamarandom** [CommonsBuild/coordination#786]
## 👇🏽  What is this issue about? Give as much detail as you can. 

How do trust levels work in Discourse. Would we benefit from integrating this in our own Discourse server? 

![IMG_FC01B5225284-1.jpeg](https://images.zenhubusercontent.com/5faaa1d038c6409364f7830c/714cff90-8c8c-4e58-b632-3a83e47af9b1)

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. Simple analysis of whether TEC can benefit from implementing this
2. Decision on whether or not to do it ;) 
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Vyvy-vi 

## 👀  Who should be in the loop about this issue?
@

**Comment by Vyvy-vi** [comment]
I think the above feature is a discourse(forum) feature, rather than a Discord feature. Moreover, this system does work on the TEC forum (*however, I'm not sure what's the set up for the eligibility of Level upgrades, and how we decide on which trust level gets attributed at which metric. if needed, we could config our to do this too)

**Comment by natenatesoo** [comment]
Is this issue active, done, or in limbo?

**Comment by Vyvy-vi** [comment]
I think there's more info and discussion needed, before this issue can be worked upon

**Comment by tamarandom** [comment]
True. I think we can close it. It should be part of a larger Discourse engagement is we take it on in the future.
