### ISSUE TITLE
DAO Tresury Legal discussions

### ISSUE THREAD

**Issue by Santigs** [CommonsBuild/coordination#882]
## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1.
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@

## 👀  Who should be in the loop about this issue?
@

**Comment by iviangita** [comment]
Closing this issue as we opened a new one: https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/issues/commonsbuild/coordination/1077 

Since only few people join the Legal bi-weekly calls and we don't have any legal expert in the group yet, we will bring the discussion to the forum so more people can engage in the discussion and get more insights.
