### ISSUE TITLE
Research on Transparency in other DAOs

### ISSUE THREAD

**Issue by iviangita** [CommonsBuild/coordination#948]
## 👇🏽  What is this issue about? Give as much detail as you can. 
Do a research on how transparency is being monitored in other DAOs

## ✨  What does success look like? (i.e., the criteria to meet to call this issue done)
1. A summary of transparency practices in other DAOs
2.
3.

## 🧍🏻‍♀️🧍🏻‍♂️  Who should be part of the Advice Process? (People who should be consulted about this issue. Those who will have valuable input.)
@Zeptimus @iviangita 

## 👀  Who should be in the loop about this issue?
@

**Comment by iviangita** [comment]
Hey @amanwithwings I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/tec-coordination-workspace-5fad0d3fbbe4da0011c2f40d/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by AL0YSI0US** [comment]
When I think of transparency in correlation to a DAO infrastructure some of these things come to mind: 
+ gated entry [NFT, POAP etc.]
+ accessibility to working documents (password protection)
+ open / private channels
+ open / private threads
+ offline message groups
+ hidden discord members (ghost players)
+ documentation 
+ Cultural practices / customs
+ accountability processes
+ governance practices
+ proposals
+ roadmaps
+ live meetings
  + recorded meetings
+ meeting notes
+ published organizational structural / teams / working groups etc.
+ open / private repositories
+ websites / social media presence
+ processes for incoming and outgoing contributors
+ published workflows
+ Mission, Vision, Values
+ Code of Conduct
+ Budget / Allocation
+ Ledgers
(I'm forgetting some things...)


> I have felt like the term transparency has been used casually in many DAO spaces.
So much comes to mind when I imagine transparency.
When I listen to others speak there is so much vagueness in what I am hearing in my travels.

I haven't looked into the TEC Transparency Working Group,
I wanna say I recall that they meet early and perhaps that's why I haven't explored the group.

+ If I'm close to something here I might be up for exploring a DAO.

**Comment by Zeptimus** [comment]
Closing, thanks @amanwithwings and AL0YSI0US
