### ISSUE TITLE
Make Forum posts for debating the Augmented Bonding Curve Parameters

### ISSUE THREAD

**Issue by GriffGreen** [CommonsBuild/coordination#96]
## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

## 🔗 Work doc - inspirational links

Hatch Thread: https://forum.tecommons.org/t/test-hatch-1-rinkeby-deployment-hatch-discussion-thread/61

Parameters for ABC are here: https://github.com/TECommons/tec-template/blob/master/scripts/new-dao.js

**Comment by natenatesoo** [comment]
Since we have a lot of parameters to define and create forum posts for, I wanted to place this within the epic so we could keep track of all the work being done.

If you are working on a forum post for the Commons Upgrade parameters, please link it within this Document!


https://docs.google.com/document/d/1Y2b5ZbiU405Efh4RYWx0Tm0F2ZAWqRgOWTbAmQOebDQ/edit?usp=sharing

**Comment by laurenluz** [comment]
@natenatesoo I made some suggestions to your entry/exit tribute post, happy to debate some of my suggested changes 😉

**Comment by laurenluz** [comment]
Made new categories on the forum for the [main params,](https://forum.tecommons.org/c/defi-legos-and-how-they-work-together/ccd-params/26) and the [advanced params](https://forum.tecommons.org/c/defi-legos-and-how-they-work-together/adv-ccd-params/27)
